myblog/main/urls.py
from django.urls import path
from main.views import HomeView, ContactView, AboutView, navigateView, ClearcacheView
from django.views.generic.base import RedirectView
from django.views.decorators.cache import cache_page

urlpatterns = [
    
    # ================================ home, contact, about urls ===========================================
    path('',HomeView.as_view(),name='homeurl'),
    path('contact/',ContactView.as_view(),name='contacturl'),
    path('contactcache/',cache_page(30) (ContactView.as_view()),name='contactcacheurl'),
    #cache will update after every 30 seconds
    path('about/',AboutView.as_view(),name='abouturl'),
    path('clearcache/',ClearcacheView.as_view(),name='clearcacheurl'),
    path('debug/',navigateView.as_view(),name='debugurl'),

    # ====================================== redirect urls =================================================
    path('home/',RedirectView.as_view(url='/'),name='homeurl'),
    path('index/',RedirectView.as_view(pattern_name='homeurl'),name='indexurl'),
    #if dynameic url has value and if nameurl is used instead of redirecting to a url then the nameurl will get the dynamic value also
    path('google/',RedirectView.as_view(url='https://www.google.com'),name='googleurl'),
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # main urls
    path('',include('main.urls')),

    # registration urls
    path('',include('registration.urls')),

    # blogpost urls
    path('',include('blogpost.urls')),
    
    # payment urls
    path('',include('payment.urls')),
    
    # session cookies urls
    path('',include('sessioncookie.urls')),
]

myblog/payment/urls.py
from django.urls import path
from payment.views import CreateModelView, UpdateModelView, DeleteModelView, ModelDetailView, ModelListView
from payment.forms import FormModelStudent, FormModelTeacher,FormModelContractor,FormModelCenter,FormModelCenterStudent, FormProxyModelCenterStudent
from payment.models import ModelStudent, ModelTeacher, ModelContractor, ModelCenter, ModelCenterStudent, ProxyModelCenterStudent
from django.contrib.auth.decorators import permission_required




urlpatterns = [
    # model student: create, update, delete, list and detail model urls 
    path('createmodelstudent/',permission_required('payment.add_modelstudent', raise_exception=True)(CreateModelView.as_view()),name='createmodelstudenturl'),

    path('updatemodelstudent/<int:pk>/',permission_required('payment.change_modelstudent', raise_exception=True)(UpdateModelView.as_view()),name='updatemodelstudenturl'),

    path('modelstudentlist/',ModelListView.as_view(),name='modelstudentlisturl'),

    path('modelstudentdetail/<int:pk>/',permission_required('payment.view_modelstudent', raise_exception=True)(ModelDetailView.as_view()),name='modelstudentdetailurl'),

    path('deletemodelstudent/<int:pk>/',permission_required('payment.delete_modelstudent', raise_exception=True)(DeleteModelView.as_view()),name='deletemodelstudenturl'),


    # model teacher: create, update, delete, list and detail model urls
    path('createmodelteacher/',permission_required('payment.add_modelteacher', raise_exception=True)(CreateModelView.as_view(form_class=FormModelTeacher,success_url = '/modelteacherlist/')),name='createmodelteacherurl'),

    path('updatemodelteacher/<int:pk>/',permission_required('payment.change_modelteacher', raise_exception=True)(UpdateModelView.as_view(form_class=FormModelTeacher,model=ModelTeacher,success_url = '/modelteacherlist/')),name='updatemodelteacherurl'),

    path('modelteacherlist/',(ModelListView.as_view(model=ModelTeacher)),name='modelteacherlisturl'),

    path('modelteacherdetail/<int:pk>/',permission_required('payment.view_modelteacher', raise_exception=True)(ModelDetailView.as_view(model=ModelTeacher)),name='modelteacherdetailurl'),

    path('deletemodelteacher/<int:pk>/',permission_required('payment.delete_modelteacher', raise_exception=True)(DeleteModelView.as_view(model=ModelTeacher,success_url = '/modelteacherlist/')),name='deletemodelteacherurl'),


    # model contractor: create, update, delete, list and detail model urls
    path('createmodelcontractor/',permission_required('payment.add_modelcontractor', raise_exception=True)(CreateModelView.as_view(form_class=FormModelContractor,success_url = '/modelcontractorlist/')),name='createmodelcontractorurl'),

    path('updatemodelcontractor/<int:pk>/',permission_required('payment.change_modelcontractor', raise_exception=True)(UpdateModelView.as_view(form_class=FormModelContractor,model=ModelContractor,success_url = '/modelcontractorlist/')),name='updatemodelcontractorurl'),

    path('modelcontractorlist/',(ModelListView.as_view(model=ModelContractor)),name='modelcontractorlisturl'),

    path('modelcontractordetail/<int:pk>/',permission_required('payment.view_modelcontractor', raise_exception=True)(ModelDetailView.as_view(model=ModelContractor)),name='modelcontractordetailurl'),

    path('deletemodelcontractor/<int:pk>/',permission_required('payment.delete_modelcontractor', raise_exception=True)(DeleteModelView.as_view(model=ModelContractor,success_url = '/modelcontractorlist/')),name='deletemodelcontractorurl'),


    # model center: create, update, delete, list and detail model urls
    path('createmodelcenter/',permission_required('payment.add_modelcenter', raise_exception=True)(CreateModelView.as_view(form_class=FormModelCenter,success_url = '/modelcenterlist/')),name='createmodelcenterurl'),

    path('updatemodelcenter/<int:pk>/',permission_required('payment.change_modelcenter', raise_exception=True)(UpdateModelView.as_view(form_class=FormModelCenter,model=ModelCenter,success_url = '/modelcenterlist/')),name='updatemodelcenterurl'),

    path('modelcenterlist/',(ModelListView.as_view(model=ModelCenter)),name='modelcenterlisturl'),

    path('modelcenterdetail/<int:pk>/',permission_required('payment.view_modelcenter', raise_exception=True)(ModelDetailView.as_view(model=ModelCenter)),name='modelcenterdetailurl'),

    path('deletemodelcenter/<int:pk>/',permission_required('payment.delete_modelcenter', raise_exception=True)(DeleteModelView.as_view(model=ModelCenter,success_url = '/modelcenterlist/')),name='deletemodelcenterurl'),


    # model center student: create, update, delete, list and detail model urls
    path('createmodelcenterstudent/',permission_required('payment.add_modelcenterstudent', raise_exception=True)(CreateModelView.as_view(form_class=FormModelCenterStudent,success_url = '/modelcenterstudentlist/')),name='createmodelcenterstudenturl'),

    path('updatemodelcenterstudent/<int:pk>/',permission_required('payment.change_modelcenterstudent', raise_exception=True)(UpdateModelView.as_view(form_class=FormModelCenterStudent,model=ModelCenterStudent,success_url = '/modelcenterstudentlist/')),name='updatemodelcenterstudenturl'),

    path('modelcenterstudentlist/',(ModelListView.as_view(model=ModelCenterStudent)),name='modelcenterstudentlisturl'),

    path('modelcenterstudentdetail/<int:pk>/',permission_required('payment.view_modelcenterstudent', raise_exception=True)(ModelDetailView.as_view(model=ModelCenterStudent)),name='modelcenterstudentdetailurl'),

    path('deletemodelcenterstudent/<int:pk>/',permission_required('payment.delete_modelcenterstudent', raise_exception=True)(DeleteModelView.as_view(model=ModelCenterStudent,success_url = '/modelcenterstudentlist/')),name='deletemodelcenterstudenturl'),


    # proxy model center student: create, update, delete, list and detail model urls
    path('createproxymodelcenterstudent/',permission_required('payment.add_proxymodelcenterstudent', raise_exception=True)(CreateModelView.as_view(form_class=FormProxyModelCenterStudent,success_url = '/proxymodelcenterstudentlist/')),name='createproxymodelcenterstudenturl'),

    path('updateproxymodelcenterstudent/<int:pk>/',permission_required('payment.change_proxymodelcenterstudent', raise_exception=True)(UpdateModelView.as_view(form_class=FormProxyModelCenterStudent,model=ProxyModelCenterStudent,success_url = '/proxymodelcenterstudentlist/')),name='updateproxymodelcenterstudenturl'),

    path('proxymodelcenterstudentlist/',(ModelListView.as_view(model=ProxyModelCenterStudent)),name='proxymodelcenterstudentlisturl'),

    path('proxymodelcenterstudentdetail/<int:pk>/',permission_required('payment.view_proxymodelcenterstudent', raise_exception=True)(ModelDetailView.as_view(model=ProxyModelCenterStudent)),name='proxymodelcenterstudentdetailurl'),

    path('deleteproxymodelcenterstudent/<int:pk>/',permission_required('payment.delete_proxymodelcenterstudent', raise_exception=True)(DeleteModelView.as_view(model=ProxyModelCenterStudent,success_url = '/proxymodelcenterstudentlist/')),name='deleteproxymodelcenterstudenturl'),
]

myblog/blogpost/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class ModelPost(models.Model):
    createdby = models.ForeignKey(User,on_delete=models.CASCADE) 
    title = models.CharField(max_length=100)
    desc = models.TextField(max_length=500)
    publish_date = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    post = models.Manager()

myblog/payment/models.py
from django.db import models

#custom model manager
# class custommanager(models.Manager):
#      def get_queryset(self):
#         return super().get_queryset().order_by('name')

# Create your models here.

#abstract model
class CommonInfo(models.Model):
    name = models.CharField(max_length=70)
    age = models.IntegerField()
    date = models.DateField()
    class Meta:
        abstract = True


class ModelStudent(CommonInfo):
    fees = models.IntegerField()
    date = None
    modelmanager = models.Manager()

class ModelTeacher(CommonInfo):
    salary = models.IntegerField()
    modelmanager = models.Manager()

class ModelContractor(CommonInfo):
    date = models.DateTimeField()
    payment = models.IntegerField()
    modelmanager = models.Manager()


#multilabel inheritance
class ModelCenter(models.Model):
    center_name = models.CharField(max_length=70)
    city = models.CharField(max_length=70)
    modelmanager = models.Manager()

class ModelCenterStudent(ModelCenter):
    name = models.CharField(max_length=70)
    roll = models.IntegerField()
    modelmanager = models.Manager()

#proxy model
class ProxyModelCenterStudent(ModelCenterStudent):
    # modelmanager = custommanager
    modelmanager = models.Manager()
    class Meta:
        proxy = True
        ordering = ['city']

myblog/payment/forms.py
from django import forms
from payment.models import ModelStudent, ModelTeacher, ModelContractor, ModelCenter, ModelCenterStudent,ProxyModelCenterStudent


class FormModelStudent(forms.ModelForm):
    class Meta:
        model = ModelStudent
        fields = ('name','age','fees')
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'age':forms.TextInput(attrs={'class':'form-control'}),
            'fees':forms.TextInput(attrs={'class':'form-control'})
        }


class FormModelTeacher(forms.ModelForm):
    class Meta:
        model = ModelTeacher
        fields = ('name','age','date','salary')
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'age':forms.TextInput(attrs={'class':'form-control'}),
            'date':forms.TextInput(attrs={'class':'form-control'}),
            'salary':forms.TextInput(attrs={'class':'form-control'})
        }
        

class FormModelContractor(forms.ModelForm):
    class Meta:
        model = ModelContractor
        fields = ('name','age','date','payment')
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'age':forms.TextInput(attrs={'class':'form-control'}),
            'date':forms.TextInput(attrs={'class':'form-control'}),
            'payment':forms.TextInput(attrs={'class':'form-control'})
        }

class FormModelCenter(forms.ModelForm):
    class Meta:
        model = ModelCenter
        fields = ('center_name','city')
        widgets = {
            'center_name':forms.TextInput(attrs={'class':'form-control'}),
            'city':forms.TextInput(attrs={'class':'form-control'}),
        }

class FormModelCenterStudent(forms.ModelForm):
    class Meta:
        model = ModelCenterStudent
        fields = ('center_name','city','name','roll')
        widgets = {
            'center_name':forms.TextInput(attrs={'class':'form-control'}),
            'city':forms.TextInput(attrs={'class':'form-control'}),
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'roll':forms.TextInput(attrs={'class':'form-control'})
        }

class FormProxyModelCenterStudent(forms.ModelForm):
    class Meta:
        model = ProxyModelCenterStudent
        fields = ('center_name','city','name','roll')
        widgets = {
            'center_name':forms.TextInput(attrs={'class':'form-control'}),
            'city':forms.TextInput(attrs={'class':'form-control'}),
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'roll':forms.TextInput(attrs={'class':'form-control'})
        }

myblog/payment/views.py
from django.shortcuts import render, HttpResponseRedirect, HttpResponse, Http404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from payment.forms import FormModelStudent
from payment.models import ModelStudent
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

# Create your views here.    

#createview
@method_decorator(login_required,name='dispatch')
class CreateModelView(CreateView):
    form_class = FormModelStudent
    template_name = 'payment/createmodel*.html'
    success_url = '/modelstudentlist/'



#updateview
@method_decorator(login_required,name='dispatch')
class UpdateModelView(UpdateView):
    model = ModelStudent
    form_class = FormModelStudent
    template_name = 'payment/createmodel*.html'
    success_url = '/modelstudentlist/'



#listview
@method_decorator(login_required,name='dispatch')
class ModelListView(ListView):
    model = ModelStudent
    template_name = 'payment/modellist*.html'
    ordering = ('id')

    # def get_queryset(self): #order by 'moh'
    #     return ModelPost.post.filter(name__icontains='moh')

# detail view for model
@method_decorator(login_required,name='dispatch')
class ModelDetailView(DetailView):
    model = ModelStudent
    template_name = 'payment/modeldetail*.html'

# delete view
@method_decorator(login_required,name='dispatch')
class DeleteModelView(DeleteView):
    model = ModelStudent
    template_name = 'payment/deletemodel.html'
    success_url = '/modelstudentlist/'

#list view
# @method_decorator(login_required,name='dispatch')
# class ModelListView(ListView):
#     template_name = 'payment/modellist*.html'
#     ordering = ('id')

#     def dispatch(self, request, *args, **kwargs):
#         models = kwargs.get('models', None)
#         if models == 'modelstudent':
#             self.model = ModelStudent
#         elif models == 'modelteacher':
#             self.model = ModelTeacher
#         return super(ModelListView, self).dispatch(request, *args, **kwargs)

#     def get_queryset(self):
        # return self.model.modelmanager.all()


#detail view
# @method_decorator(login_required,name='dispatch')
# class ModelDetailView(DetailView):
#     template_name = 'payment/modeldetail*.html'

#     def dispatch(self, request, *args, **kwargs):
#         models = kwargs.get('models', None)
#         if models == 'modelstudent':
#             self.model = ModelStudent
#         elif models == 'modelteacher':
#             self.model = ModelTeacher
#         return super(ModelDetailView, self).dispatch(request, *args, **kwargs)

#     def get_queryset(self):
#         return self.model.modelmanager.all()



#delete view
# @method_decorator(login_required,name='dispatch')
# class DeleteModelView(DeleteView):
#     template_name = 'payment/deletemodel.html'
#     success_url = '/'

#     def dispatch(self, request, *args, **kwargs):
#         models = kwargs.get('models', None)
#         if models == 'modelstudent':
#             self.model = ModelStudent
#         elif models == 'modelteacher':
#             self.model = ModelTeacher
#         return super(DeleteModelView, self).dispatch(request, *args, **kwargs)

#     def get_queryset(self):
#         return self.model.modelmanager.all()

myblog/payment/templates/payment/createmodel*.html
{% extends 'payment/paymentlayout.html' %}
{% load static %}
{% block title %}
create model
{% endblock title %}
{% block body %}
<h1>this is create model page</h1>
<form action="" method="post" novalidate>
    {% csrf_token %}
    {% include 'global/form.html' %}
    <input type="submit" value="save">
</form>
<a href="#">cancel</a>
{% endblock body %}

myblog/payment/templates/payment/deletemodel.html
{% extends 'payment/paymentlayout.html' %}
{% load static %}
{% block title %}
delete model
{% endblock title %}
{% block body %}
<h1>confirm delete ! Are you sure?</h1>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="delete">
    </form>
    <a href="#">cancel</a>
{% endblock body %}

myblog/payment/templates/payment/modeldetail*.html
{% extends 'payment/paymentlayout.html' %}
{% load static %}
{% block title %}
create model
{% endblock title %}
{% block body %}
<h1>this is model detail page</h1>

{% if modelstudent %}
<table class="table">
  <tr>
    <th>id:</th>
    <td>{{modelstudent.id}}</td>
  </tr>
  <tr>
    <th>name:</th>
    <td>{{modelstudent.name}}</td>
  </tr>
  <tr>
    <th>age:</th>
    <td>{{modelstudent.age}}</td>
  </tr>
  <tr>
    <th>fees:</th>
    <td>{{modelstudent.fees}}</td>
  </tr>
  {% if perms.payment.change_modelstudent %}
    <tr>
      <td>
      <a href="{% url 'updatemodelstudenturl' modelstudent.id %}" class="btn btn-warning " >edit</a>
  {% endif %}
      
  {% if perms.payment.delete_modelstudent %}
      <a href="{% url 'deletemodelstudenturl' modelstudent.id %}" class="btn btn-danger " >delete</a>
  {% endif %}
      </td>
    </tr>

</table>
{% endif %}

{% if modelteacher %}
<table class="table">
  <tr>
    <th>id:</th>
    <td>{{modelteacher.id}}</td>
  </tr>
  <tr>
    <th>name:</th>
    <td>{{modelteacher.name}}</td>
  </tr>
  <tr>
    <th>age:</th>
    <td>{{modelteacher.age}}</td>
  </tr>
  <tr>
    <th>date:</th>
    <td>{{modelteacher.date}}</td>
  </tr>
  <tr>
    <th>salary:</th>
    <td>{{modelteacher.salary}}</td>
  </tr>
  {% if perms.blogpost.change_modelpost %}
    <tr>
      <td>
      <a href="{% url 'updatemodelteacherurl' modelteacher.id %}" class="btn btn-warning " >edit</a>
  {% endif %}
      
  {% if perms.blogpost.delete_modelpost %}
      <a href="{% url 'deletemodelteacherurl' modelteacher.id %}" class="btn btn-danger " >delete</a>
  {% endif %}
      </td>
    </tr>

  </table>
{% endif %}

{% if modelcontractor %}
<table class="table">
  <tr>
    <th>id:</th>
    <td>{{modelcontractor.id}}</td>
  </tr>
  <tr>
    <th>name:</th>
    <td>{{modelcontractor.name}}</td>
  </tr>
  <tr>
    <th>age:</th>
    <td>{{modelcontractor.age}}</td>
  </tr>
  <tr>
    <th>date:</th>
    <td>{{modelcontractor.date}}</td>
  </tr>
  <tr>
    <th>payment:</th>
    <td>{{modelcontractor.payment}}</td>
  </tr>
  {% if perms.blogpost.change_modelpost %}
    <tr>
      <td>
      <a href="{% url 'updatemodelcontractorurl' modelcontractor.id %}" class="btn btn-warning " >edit</a>
  {% endif %}
      
  {% if perms.blogpost.delete_modelpost %}
      <a href="{% url 'deletemodelcontractorurl' modelcontractor.id %}" class="btn btn-danger " >delete</a>
  {% endif %}
      </td>
    </tr>

  </table>
{% endif %}

{% if modelcenter %}
<table class="table">
  <tr>
    <th>id:</th>
    <td>{{modelcenter.id}}</td>
  </tr>
  <tr>
    <th>center name:</th>
    <td>{{modelcenter.center_name}}</td>
  </tr>
  <tr>
    <th>city:</th>
    <td>{{modelcenter.city}}</td>
  </tr>
  {% if perms.blogpost.change_modelpost %}
    <tr>
      <td>
      <a href="{% url 'updatemodelcenterurl' modelcenter.id %}" class="btn btn-warning " >edit</a>
  {% endif %}
      
  {% if perms.blogpost.delete_modelpost %}
      <a href="{% url 'deletemodelcenterurl' modelcenter.id %}" class="btn btn-danger " >delete</a>
  {% endif %}
      </td>
    </tr>

  </table>
{% endif %}

{% if modelcenterstudent %}
<table class="table">
  <tr>
    <th>id:</th>
    <td>{{modelcenterstudent.id}}</td>
  </tr>
  <tr>
    <th>center name:</th>
    <td>{{modelcenterstudent.center_name}}</td>
  </tr>
  <tr>
    <th>city:</th>
    <td>{{modelcenterstudent.city}}</td>
  </tr>
  <tr>
    <th>name:</th>
    <td>{{modelcenterstudent.name}}</td>
  </tr>
  <tr>
    <th>roll:</th>
    <td>{{modelcenterstudent.roll}}</td>
  </tr>
  {% if perms.blogpost.change_modelpost %}
    <tr>
      <td>
      <a href="{% url 'updatemodelcenterstudenturl' modelcenterstudent.id %}" class="btn btn-warning " >edit</a>
  {% endif %}
      
  {% if perms.blogpost.delete_modelpost %}
      <a href="{% url 'deletemodelcenterstudenturl' modelcenterstudent.id %}" class="btn btn-danger " >delete</a>
  {% endif %}
      </td>
    </tr>

  </table>
{% endif %}

{% if proxymodelcenterstudent %}
<table class="table">
  <tr>
    <th>id:</th>
    <td>{{proxymodelcenterstudent.id}}</td>
  </tr>
  <tr>
    <th>center name:</th>
    <td>{{proxymodelcenterstudent.center_name}}</td>
  </tr>
  <tr>
    <th>city:</th>
    <td>{{proxymodelcenterstudent.city}}</td>
  </tr>
  <tr>
    <th>name:</th>
    <td>{{proxymodelcenterstudent.name}}</td>
  </tr>
  <tr>
    <th>roll:</th>
    <td>{{proxymodelcenterstudent.roll}}</td>
  </tr>
  {% if perms.blogpost.change_modelpost %}
    <tr>
      <td>
      <a href="{% url 'updateproxymodelcenterstudenturl' proxymodelcenterstudent.id %}" class="btn btn-warning " >edit</a>
  {% endif %}
      
  {% if perms.blogpost.delete_modelpost %}
      <a href="{% url 'deleteproxymodelcenterstudenturl' proxymodelcenterstudent.id %}" class="btn btn-danger " >delete</a>
  {% endif %}
      </td>
    </tr>

  </table>
{% endif %}
<br>
<a href="#">home</a>
{% endblock body %}

myblog/payment/templates/payment/modellist*.html
{% extends 'payment/paymentlayout.html' %}
{% load static %}
{% block title %}
create model
{% endblock title %}
{% block body %}
<h1>this is model list page</h1>

{% if modelstudent_list %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">name</th>
        <th scope="col">age</th>
        <th scope="col">fees</th>
        <th scope="col">details</th>
      </tr>
    </thead>
    
    <tbody>
      {% for field in modelstudent_list %}
      <tr>
        <th scope="row">{{field.id}}</th>
        <td>{{field.name}}</td>
        <td>{{field.age}}</td>
        <td>{{field.fees}}</td>
        <td><a href="{% url 'modelstudentdetailurl' field.id %}" class="btn btn-primary " >view</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% endif %}

{% if modelteacher_list %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">name</th>
        <th scope="col">age</th>
        <th scope="col">date</th>
        <th scope="col">salary</th>
        <th scope="col">details</th>
      </tr>
    </thead>
    
    <tbody>
      {% for field in modelteacher_list %}
      <tr>
        <th scope="row">{{field.id}}</th>
        <td>{{field.name}}</td>
        <td>{{field.age}}</td>
        <td>{{field.date}}</td>
        <td>{{field.salary}}</td>
        <td><a href="{% url 'modelteacherdetailurl' field.id %}" class="btn btn-primary " >view</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% endif %}

{% if modelcontractor_list %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">name</th>
        <th scope="col">age</th>
        <th scope="col">date</th>
        <th scope="col">payment</th>
        <th scope="col">details</th>
      </tr>
    </thead>
    
    <tbody>
      {% for field in modelcontractor_list %}
      <tr>
        <th scope="row">{{field.id}}</th>
        <td>{{field.name}}</td>
        <td>{{field.age}}</td>
        <td>{{field.date}}</td>
        <td>{{field.payment}}</td>
        <td><a href="{% url 'modelcontractordetailurl' field.id %}" class="btn btn-primary " >view</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% endif %}

{% if modelcenter_list %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">center name</th>
        <th scope="col">city</th>
        <th scope="col">details</th>
      </tr>
    </thead>
    
    <tbody>
      {% for field in modelcenter_list %}
      <tr>
        <th scope="row">{{field.id}}</th>
        <td>{{field.center_name}}</td>
        <td>{{field.city}}</td>
        <td><a href="{% url 'modelcenterdetailurl' field.id %}" class="btn btn-primary " >view</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% endif %}

{% if modelcenterstudent_list %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">center name</th>
        <th scope="col">city</th>
        <th scope="col">name</th>
        <th scope="col">roll</th>
        <th scope="col">details</th>
      </tr>
    </thead>
    
    <tbody>
      {% for field in modelcenterstudent_list %}
      <tr>
        <th scope="row">{{field.id}}</th>
        <td>{{field.center_name}}</td>
        <td>{{field.city}}</td>
        <td>{{field.name}}</td>
        <td>{{field.roll}}</td>
        <td><a href="{% url 'modelcenterstudentdetailurl' field.id %}" class="btn btn-primary " >view</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% endif %}

{% if proxymodelcenterstudent_list %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">center name</th>
        <th scope="col">city</th>
        <th scope="col">name</th>
        <th scope="col">roll</th>
        <th scope="col">details</th>
      </tr>
    </thead>
    
    <tbody>
      {% for field in proxymodelcenterstudent_list %}
      <tr>
        <th scope="row">{{field.id}}</th>
        <td>{{field.center_name}}</td>
        <td>{{field.city}}</td>
        <td>{{field.name}}</td>
        <td>{{field.roll}}</td>
        <td><a href="{% url 'proxymodelcenterstudentdetailurl' field.id %}" class="btn btn-primary " >view</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% endif %}
   <br>
<a href="#">home</a>
{% endblock body %}